#!/usr/bin/env bash
# Real-hardware acceptance check for CH-8. This intentionally does not mock
# Cloud Hypervisor or VFIO: it proves that the configured host PCI identity is
# enumerated by a running guest and records JSON evidence beside VM state.

set -euo pipefail

usage() {
    cat <<'EOF'
Usage: verify-ch-gpu-passthrough.sh VM_NAME [OPTIONS]

Options:
  --host IP          Guest IP (otherwise read vm-info.json or the IP registry).
  --user USER        SSH user (default: agent).
  --key PATH         SSH private key.
  --timeout SEC      SSH connect timeout (default: 10).
  --evidence PATH    Evidence JSON path (default: <vm>/cloud-hypervisor/gpu-validation.json).
  --skip-driver-probe
                     Record PCI enumeration without running nvidia-smi. Required
                     before a tenant-B pre-write VRAM residue probe.
  -h, --help         Show this help.
EOF
}

VM_NAME=""
GUEST_HOST=""
SSH_USER="agent"
SSH_KEY=""
SSH_TIMEOUT=10
EVIDENCE_PATH=""
SKIP_DRIVER_PROBE=false
VM_STORAGE_DIR="${VM_STORAGE_DIR:-/var/lib/agentic-sandbox/vms}"
IP_REGISTRY="${IP_REGISTRY:-$VM_STORAGE_DIR/.ip-registry}"
PCI_SYSFS_ROOT="${AGENTIC_CH_PCI_SYSFS_ROOT:-/sys/bus/pci}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --host) GUEST_HOST="${2:?--host requires an IP}"; shift 2 ;;
        --user) SSH_USER="${2:?--user requires a value}"; shift 2 ;;
        --key) SSH_KEY="${2:?--key requires a path}"; shift 2 ;;
        --timeout) SSH_TIMEOUT="${2:?--timeout requires seconds}"; shift 2 ;;
        --evidence) EVIDENCE_PATH="${2:?--evidence requires a path}"; shift 2 ;;
        --skip-driver-probe) SKIP_DRIVER_PROBE=true; shift ;;
        -h|--help) usage; exit 0 ;;
        -*) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
        *)
            [[ -z "$VM_NAME" ]] || { echo "VM name specified more than once" >&2; exit 2; }
            VM_NAME="$1"
            shift
            ;;
    esac
done

[[ -n "$VM_NAME" ]] || { usage >&2; exit 2; }
[[ "$SSH_TIMEOUT" =~ ^[1-9][0-9]*$ ]] || { echo "--timeout must be a positive integer" >&2; exit 2; }
command -v jq >/dev/null 2>&1 || { echo "jq is required" >&2; exit 1; }
command -v ssh >/dev/null 2>&1 || { echo "ssh is required" >&2; exit 1; }

state_dir="$VM_STORAGE_DIR/$VM_NAME/cloud-hypervisor"
state_file="$state_dir/vm.env"
[[ -f "$state_file" ]] || { echo "Cloud Hypervisor state not found: $state_file" >&2; exit 1; }

# vm.env is generated by the backend and shell-quotes every value.
# shellcheck source=/dev/null
source "$state_file"
[[ "${GPU_ENABLED:-false}" == "true" ]] || { echo "VM is not GPU-enabled: $VM_NAME" >&2; exit 1; }
[[ -n "${GPU_PCI_DEVICE:-}" ]] || { echo "GPU_PCI_DEVICE is missing from $state_file" >&2; exit 1; }

host_device="$PCI_SYSFS_ROOT/devices/$GPU_PCI_DEVICE"
[[ -d "$host_device" ]] || { echo "Host PCI device not found: $host_device" >&2; exit 1; }
[[ -r "$host_device/vendor" && -r "$host_device/device" && -r "$host_device/class" ]] \
    || { echo "Host PCI identity is unreadable: $host_device" >&2; exit 1; }
vendor="$(<"$host_device/vendor")"
device="$(<"$host_device/device")"
class_code="$(<"$host_device/class")"
vendor="${vendor#0x}"
device="${device#0x}"
vendor_device="${vendor,,}:${device,,}"
class_code="${class_code,,}"
[[ "$class_code" =~ ^0x03[0-9a-f]{4}$ ]] \
    || { echo "Configured primary is not a GPU/display-class PCI device: $GPU_PCI_DEVICE ($class_code)" >&2; exit 1; }

[[ -L "$host_device/iommu_group" ]] \
    || { echo "Host GPU has no IOMMU group: $GPU_PCI_DEVICE" >&2; exit 1; }
group_dir="$(readlink -f "$host_device/iommu_group")"
group_id="$(basename "$group_dir")"
mapfile -t group_members < <(find "$group_dir/devices" -mindepth 1 -maxdepth 1 -printf '%f\n' | sort)
[[ ${#group_members[@]} -gt 0 ]] || { echo "IOMMU group $group_id has no members" >&2; exit 1; }
for member in "${group_members[@]}"; do
    member_driver="$(basename "$(readlink -f "$PCI_SYSFS_ROOT/devices/$member/driver" 2>/dev/null)" 2>/dev/null || true)"
    [[ "$member_driver" == "vfio-pci" ]] \
        || { echo "IOMMU group member is not bound to vfio-pci: $member ($member_driver)" >&2; exit 1; }
done
group_members_json="$(printf '%s\n' "${group_members[@]}" | jq -Rsc 'split("\n") | map(select(length > 0))')"
reset_method=""
if [[ -r "$host_device/reset_method" ]]; then
    reset_method="$(tr '\n' ' ' < "$host_device/reset_method" | sed 's/[[:space:]]*$//')"
fi

[[ -n "${API_SOCKET:-}" && -S "$API_SOCKET" ]] \
    || { echo "Cloud Hypervisor API socket is unavailable: ${API_SOCKET:-unset}" >&2; exit 1; }
ch_remote="${AGENTIC_CH_REMOTE_BIN:-}"
if [[ -z "$ch_remote" ]]; then
    ch_remote="$(command -v ch-remote || true)"
fi
if [[ -z "$ch_remote" && -x /opt/agentic-sandbox/cloud-hypervisor/current/bin/ch-remote ]]; then
    ch_remote=/opt/agentic-sandbox/cloud-hypervisor/current/bin/ch-remote
fi
[[ -n "$ch_remote" ]] || { echo "ch-remote is required to verify live device attachment" >&2; exit 1; }
ch_info="$("$ch_remote" --api-socket "$API_SOCKET" info)"
expected_device_path="$host_device/"
ch_device_path="$(jq -r --arg path "$expected_device_path" \
    '.config.devices[]? | select((.path | rtrimstr("/")) == ($path | rtrimstr("/"))) | .path' \
    <<<"$ch_info" | head -n1)"
[[ -n "$ch_device_path" ]] \
    || { echo "Live Cloud Hypervisor config does not contain --device path=$expected_device_path" >&2; exit 1; }

if [[ -z "$GUEST_HOST" ]]; then
    vm_info="$VM_STORAGE_DIR/$VM_NAME/vm-info.json"
    if [[ -f "$vm_info" ]]; then
        GUEST_HOST="$(jq -r '.ip // empty' "$vm_info")"
    fi
fi
if [[ -z "$GUEST_HOST" && -f "$IP_REGISTRY" ]]; then
    GUEST_HOST="$(awk -F= -v vm="$VM_NAME" '$1 == vm { print $2; exit }' "$IP_REGISTRY")"
fi
[[ -n "$GUEST_HOST" ]] || { echo "Guest IP unavailable; pass --host" >&2; exit 1; }

ssh_args=(
    -o BatchMode=yes
    -o StrictHostKeyChecking=accept-new
    -o "ConnectTimeout=$SSH_TIMEOUT"
)
if [[ -n "$SSH_KEY" ]]; then
    [[ -r "$SSH_KEY" ]] || { echo "SSH key is unreadable: $SSH_KEY" >&2; exit 1; }
    ssh_args+=(-i "$SSH_KEY")
fi

guest_output="$(
    ssh "${ssh_args[@]}" "$SSH_USER@$GUEST_HOST" \
        'command -v lspci >/dev/null || { echo "pciutils/lspci is missing" >&2; exit 127; }; lspci -Dn'
)"
guest_line="$(printf '%s\n' "$guest_output" | awk -v id="$vendor_device" \
    'tolower($0) ~ ("[[:space:]]" id "([[:space:]]|$)") { print; exit }')"
if [[ -z "$guest_line" ]]; then
    echo "Guest did not enumerate host PCI ID $vendor_device" >&2
    printf '%s\n' "$guest_output" >&2
    exit 1
fi

nvidia_output=""
if [[ "${vendor,,}" == "10de" && "$SKIP_DRIVER_PROBE" != true ]]; then
    nvidia_output="$(
        ssh "${ssh_args[@]}" "$SSH_USER@$GUEST_HOST" \
            'if command -v nvidia-smi >/dev/null; then nvidia-smi -L; fi'
    )"
fi

EVIDENCE_PATH="${EVIDENCE_PATH:-$state_dir/gpu-validation.json}"
mkdir -p "$(dirname "$EVIDENCE_PATH")"
jq -n \
    --arg checked_at "$(date --utc +%Y-%m-%dT%H:%M:%SZ)" \
    --arg vm "$VM_NAME" \
    --arg host_bdf "$GPU_PCI_DEVICE" \
    --arg vendor_device "$vendor_device" \
    --arg class_code "$class_code" \
    --arg iommu_group "$group_id" \
    --argjson iommu_group_members "$group_members_json" \
    --arg reset_method "$reset_method" \
    --arg ch_device_path "$ch_device_path" \
    --arg guest_host "$GUEST_HOST" \
    --arg guest_lspci "$guest_line" \
    --arg nvidia_smi "$nvidia_output" \
    --argjson driver_probe_skipped "$SKIP_DRIVER_PROBE" \
    '{
      checked_at: $checked_at,
      backend: "cloud-hypervisor",
      vm: $vm,
      host_bdf: $host_bdf,
      vendor_device: $vendor_device,
      class_code: $class_code,
      iommu_group: $iommu_group,
      iommu_group_members: $iommu_group_members,
      reset_method: (if $reset_method == "" then null else $reset_method end),
      group_all_vfio: true,
      cloud_hypervisor_device_attached: true,
      cloud_hypervisor_device_path: $ch_device_path,
      guest_host: $guest_host,
      guest_enumerated: true,
      guest_lspci: $guest_lspci,
      driver_probe_skipped: $driver_probe_skipped,
      nvidia_smi: (if $nvidia_smi == "" then null else $nvidia_smi end)
    }' > "$EVIDENCE_PATH"

printf 'PASS: guest %s enumerated host GPU %s (%s)\n' "$VM_NAME" "$GPU_PCI_DEVICE" "$vendor_device"
printf 'Evidence: %s\n' "$EVIDENCE_PATH"
