//! Formal PTY session multiplexing layer.
//!
//! A [`Session`] is the durable unit of PTY multiplexing.  It outlives
//! individual command invocations and client connections.  Multiple clients
//! may attach concurrently, but controller authority is leased to at most
//! one live attachment at a time. Additional controller requests are
//! downgraded to [`Role::Observer`] until the controller detaches or its
//! channel is reaped as stale. Observer attachments are locked read-only.
//!
//! **The server owns all state.**  Clients are dumb connectors — they join,
//! receive a stream of sequenced [`SessionFrame`]s, and detach without
//! killing the session.

mod redaction;
pub mod registry;
pub mod replay;
pub mod transcript;

pub use registry::{Session, SessionAttachment, SessionRegistry};
pub use replay::{ReplayBuffer, RingEntry, RingEntryKind};
pub use transcript::{TranscriptArchive, TranscriptMetrics, TranscriptQuery, TranscriptRecord};

use serde::{Deserialize, Serialize};

/// Stable session identifier (UUIDv7).  Survives command_id changes on
/// agent reconnect.
pub type SessionId = String;

/// Per-connection client identifier (UUIDv4, assigned on WS attach).
pub type ClientId = String;

// ── Role ─────────────────────────────────────────────────────────────────────

/// Role of a client within a session.
///
/// Set at attach time and fixed for the lifetime of that attachment.
/// At most one `Controller` may exist in the formal WS registry; observers
/// are locked read-only until they re-attach and the lease is available.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    /// May send stdin and resize frames. Singleton lease holder.
    Controller,
    /// Read-only; receives all output frames.
    Observer,
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Role::Controller => write!(f, "controller"),
            Role::Observer => write!(f, "observer"),
        }
    }
}

impl Role {
    pub fn from_str(s: &str) -> Self {
        match s {
            "controller" => Role::Controller,
            _ => Role::Observer,
        }
    }
}

// ── Wire frame ────────────────────────────────────────────────────────────────

/// The fundamental unit emitted to every client attached to a session.
///
/// `seq` is monotonically increasing per session.  Clients use it to detect
/// gaps and to request replay from a specific point after reconnect.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionFrame {
    pub session_id: SessionId,
    /// Monotonically increasing per-session sequence number.
    pub seq: u64,
    /// Unix timestamp in milliseconds.
    pub ts: i64,
    #[serde(flatten)]
    pub payload: SessionPayload,
}

/// Content of a [`SessionFrame`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum SessionPayload {
    /// Raw PTY bytes from the running process.
    Output {
        stream: StreamKind,
        /// Base64-encoded binary PTY data (binary-safe).
        data: String,
    },
    /// Periodic full-repaint snapshot suitable as a safe replay starting
    /// point. Same wire shape as `Output` (stream + base64 data) so dumb
    /// clients can render it identically; smarter clients (#144) treat
    /// it as a "before this point you can drop your terminal state" mark.
    /// Generated by the server's screen-state tracker via
    /// `vt100::Screen::contents_formatted()` — see #145.
    Keyframe { stream: StreamKind, data: String },
    /// Terminal dimensions changed; broadcast to all clients.
    Resize { cols: u16, rows: u16 },
    /// The caller's role in this session was (re)assigned.
    RoleAssigned { role: Role },
    /// Session membership changed (client attached/detached).
    /// Broadcast to every attached client so UIs can render participant lists.
    MembershipChanged {
        controllers: Vec<ClientId>,
        observers: Vec<ClientId>,
    },
    /// Session ended (process exited or was killed).
    Closed { exit_code: Option<i32> },
    /// Session-level error.
    Error { message: String },
}

/// PTY output stream discriminant (stdout / stderr / log).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StreamKind {
    Stdout,
    Stderr,
    Log,
}

impl std::fmt::Display for StreamKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StreamKind::Stdout => write!(f, "stdout"),
            StreamKind::Stderr => write!(f, "stderr"),
            StreamKind::Log => write!(f, "log"),
        }
    }
}
