# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """AgentService - Primary communication channel between management and agents

    Flow:
    1. Agent boots, establishes gRPC connection to management server
    2. Agent calls Connect() with bidirectional stream
    3. Management sends commands via stream
    4. Agent sends outputs (stdout, stderr, logs, status) via stream

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/agentic.sandbox.v1.AgentService/Connect',
                request_serializer=agent__pb2.AgentMessage.SerializeToString,
                response_deserializer=agent__pb2.ManagementMessage.FromString,
                _registered_method=True)
        self.Exec = channel.unary_stream(
                '/agentic.sandbox.v1.AgentService/Exec',
                request_serializer=agent__pb2.ExecRequest.SerializeToString,
                response_deserializer=agent__pb2.ExecOutput.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AgentService - Primary communication channel between management and agents

    Flow:
    1. Agent boots, establishes gRPC connection to management server
    2. Agent calls Connect() with bidirectional stream
    3. Management sends commands via stream
    4. Agent sends outputs (stdout, stderr, logs, status) via stream

    """

    def Connect(self, request_iterator, context):
        """Connect establishes a bidirectional stream between agent and management.
        Agent sends: registration, stdout/stderr, logs, heartbeats, command results
        Management sends: commands, config updates, shutdown signals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Exec runs a one-shot command and streams output (simpler than Connect for quick ops)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=agent__pb2.AgentMessage.FromString,
                    response_serializer=agent__pb2.ManagementMessage.SerializeToString,
            ),
            'Exec': grpc.unary_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=agent__pb2.ExecRequest.FromString,
                    response_serializer=agent__pb2.ExecOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentic.sandbox.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentic.sandbox.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService - Primary communication channel between management and agents

    Flow:
    1. Agent boots, establishes gRPC connection to management server
    2. Agent calls Connect() with bidirectional stream
    3. Management sends commands via stream
    4. Agent sends outputs (stdout, stderr, logs, status) via stream

    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agentic.sandbox.v1.AgentService/Connect',
            agent__pb2.AgentMessage.SerializeToString,
            agent__pb2.ManagementMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agentic.sandbox.v1.AgentService/Exec',
            agent__pb2.ExecRequest.SerializeToString,
            agent__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
