#!/bin/bash
# backends/libvirt.sh — Libvirt/KVM backend for VM lifecycle operations
#
# Implements the backend interface using virsh and qemu-img.
# This is a faithful extraction of the virsh logic that previously lived
# directly in provision-vm.sh (define_vm, provision_vm, add_dhcp_reservation,
# get_vm_ip, and related helpers).
#
# All functions are prefixed _backend_libvirt_ and must not be called
# directly — use the backend_* dispatcher functions from lib/platform.sh.
#
# Dependencies: virsh, qemu-img, jq
# Consumed variables from provision-vm.sh scope (set before sourcing):
#   AGENTSHARE_ROOT  — root directory for virtiofs shares

set -euo pipefail

# ---------------------------------------------------------------------------
# _backend_libvirt_create_vm
#
# Creates a QEMU/KVM VM definition in libvirt from a pre-built disk image and
# cloud-init ISO.  Generates the domain XML and calls `virsh define`.
#
# Args:
#   $1  vm_name
#   $2  disk_path          — path to qcow2 overlay disk
#   $3  cloud_init_iso     — path to cloud-init ISO
#   $4  cpus
#   $5  memory_mb
#   $6  network            — libvirt network name (e.g. "default")
#   $7  mac_address        — (optional) deterministic MAC
#   $8  use_agentshare     — "true"|"false"
#   $9  inbox_path         — host path for agentinbox virtiofs mount
#   $10 outbox_path        — (optional) host path for agentoutbox virtiofs mount
#   $11 mem_limit_mb       — hard memory limit in MiB
#   $12 cpu_quota_pct      — CPU quota percent (e.g. 400 for 4 vCPUs * 100%)
#   $13 io_weight          — blkio weight 100-1000
#   $14 io_read_bps        — read bandwidth limit in bytes/sec
#   $15 io_write_bps       — write bandwidth limit in bytes/sec
#
# Outputs: path to the generated XML file (stdout)
# ---------------------------------------------------------------------------
_backend_libvirt_create_vm() {
    local vm_name="$1"
    local disk_path="$2"
    local cloud_init_iso="$3"
    local cpus="$4"
    local memory_mb="$5"
    local network="$6"
    local mac_address="${7:-}"
    local use_agentshare="${8:-false}"
    local inbox_path="${9:-}"
    local outbox_path="${10:-}"

    # Resource limit parameters
    local mem_limit_mb="${11:-$memory_mb}"
    local cpu_quota_pct="${12:-$((cpus * 100))}"
    local io_weight="${13:-500}"
    local io_read_bps="${14:-524288000}"
    local io_write_bps="${15:-209715200}"

    # GPU passthrough config (optional, generated by loadout system)
    local gpu_config_path="${16:-}"

    # Generate libvirt XML alongside the disk
    local xml_path="${disk_path%.qcow2}.xml"

    # MAC address element (empty lets libvirt auto-generate)
    local mac_element=""
    if [[ -n "$mac_address" ]]; then
        mac_element="<mac address='$mac_address'/>"
    fi

    # Build virtiofs XML blocks
    local virtiofs_elements=""
    local memoryBacking=""
    if [[ "$use_agentshare" == "true" && -n "$inbox_path" ]]; then
        # memfd backing is required for virtiofs shared memory
        memoryBacking="
  <memoryBacking>
    <source type='memfd'/>
    <access mode='shared'/>
  </memoryBacking>"

        # Note: virtiofs does not support <readonly/> in libvirt XML.
        # Read-only enforcement is done via mount options in cloud-init.
        virtiofs_elements="
    <filesystem type='mount' accessmode='passthrough'>
      <driver type='virtiofs'/>
      <source dir='${AGENTSHARE_ROOT:-/srv/agentshare}/global-ro'/>
      <target dir='agentglobal'/>
    </filesystem>
    <filesystem type='mount' accessmode='passthrough'>
      <driver type='virtiofs'/>
      <source dir='$inbox_path'/>
      <target dir='agentinbox'/>
    </filesystem>"

        # Outbox mount is optional (task orchestration mode)
        if [[ -n "$outbox_path" ]]; then
            virtiofs_elements+="
    <filesystem type='mount' accessmode='passthrough'>
      <driver type='virtiofs'/>
      <source dir='$outbox_path'/>
      <target dir='agentoutbox'/>
    </filesystem>"
        fi
    fi

    # GPU passthrough hostdev element
    local gpu_hostdev=""
    if [[ -n "$gpu_config_path" && -f "$gpu_config_path" ]]; then
        # shellcheck source=/dev/null
        source "$gpu_config_path"
        if [[ "${GPU_ENABLED:-false}" == "true" && -n "${GPU_PCI_DEVICE:-}" ]]; then
            # Parse PCI address: domain:bus:slot.function (e.g. 0000:01:00.0)
            local pci_domain pci_bus pci_slot pci_function
            pci_domain="0x${GPU_PCI_DEVICE%%:*}"
            local rest="${GPU_PCI_DEVICE#*:}"
            pci_bus="0x${rest%%:*}"
            rest="${rest#*:}"
            pci_slot="0x${rest%%.*}"
            pci_function="0x${rest##*.}"
            gpu_hostdev="
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address domain='$pci_domain' bus='$pci_bus' slot='$pci_slot' function='$pci_function'/>
      </source>
    </hostdev>"
        fi
    fi

    cat > "$xml_path" <<EOF
<domain type='kvm'>
  <name>$vm_name</name>
  <memory unit='MiB'>$memory_mb</memory>
  <vcpu placement='static'>$cpus</vcpu>$memoryBacking
  <memtune>
    <hard_limit unit='MiB'>$((mem_limit_mb + 256))</hard_limit>
    <soft_limit unit='MiB'>$mem_limit_mb</soft_limit>
  </memtune>
  <cputune>
    <shares>$((cpus * 1024))</shares>
    <period>100000</period>
    <quota>$((cpu_quota_pct * 1000))</quota>
  </cputune>
  <blkiotune>
    <weight>$io_weight</weight>
  </blkiotune>
  <os>
    <type arch='x86_64' machine='q35'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode='host-passthrough'/>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='writeback'/>
      <source file='$disk_path'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='$cloud_init_iso'/>
      <target dev='sda' bus='sata'/>
      <readonly/>
    </disk>
    <interface type='network'>
      <source network='$network'/>
      $mac_element
      <model type='virtio'/>
    </interface>$virtiofs_elements$gpu_hostdev
    <channel type='unix'>
      <target type='virtio' name='org.qemu.guest_agent.0'/>
    </channel>
    <serial type='pty'>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <graphics type='vnc' port='-1' autoport='yes'/>
  </devices>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
</domain>
EOF

    virsh define "$xml_path" > /dev/null
    echo "$xml_path"
}

# ---------------------------------------------------------------------------
# _backend_libvirt_attach_cloud_init
#
# Attaches (or re-attaches) a cloud-init ISO as a CDROM device to an existing
# VM definition.  Used when reprovisioning without recreating the whole VM.
#
# Args:
#   $1  vm_name
#   $2  cloud_init_iso  — path to the ISO file
# ---------------------------------------------------------------------------
_backend_libvirt_attach_cloud_init() {
    local vm_name="$1"
    local cloud_init_iso="$2"

    virsh attach-disk "$vm_name" "$cloud_init_iso" sda \
        --type cdrom --mode readonly --config 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# _backend_libvirt_configure_virtiofs
#
# Adds virtiofs filesystem devices and the required memfd memory backing to an
# existing VM definition (in-place XML update via virsh).
#
# In practice, virtiofs configuration is embedded in the XML at define time by
# _backend_libvirt_create_vm.  This function is provided for completeness and
# for use when adding virtiofs to a VM that was defined without it.
#
# Args:
#   $1  vm_name
#   $2  inbox_path
#   $3  outbox_path  (optional)
# ---------------------------------------------------------------------------
_backend_libvirt_configure_virtiofs() {
    local vm_name="$1"
    local inbox_path="$2"
    local outbox_path="${3:-}"

    log_warn "configure_virtiofs: live XML update not supported — recreate VM to change virtiofs config"
    log_info "Use backend_destroy_vm + backend_create_vm with use_agentshare=true to reconfigure"
    return 1
}

# ---------------------------------------------------------------------------
# _backend_libvirt_start_vm
#
# Starts a previously defined VM.
#
# Args:
#   $1  vm_name
# ---------------------------------------------------------------------------
_backend_libvirt_start_vm() {
    local vm_name="$1"
    virsh start "$vm_name" > /dev/null
}

# ---------------------------------------------------------------------------
# _backend_libvirt_stop_vm
#
# Sends ACPI shutdown to a running VM (graceful).
#
# Args:
#   $1  vm_name
# ---------------------------------------------------------------------------
_backend_libvirt_stop_vm() {
    local vm_name="$1"
    virsh shutdown "$vm_name"
}

# ---------------------------------------------------------------------------
# _backend_libvirt_destroy_vm
#
# Force-kills and permanently undefines a VM, removing all associated storage.
# This is destructive and irreversible.
#
# Args:
#   $1  vm_name
# ---------------------------------------------------------------------------
_backend_libvirt_destroy_vm() {
    local vm_name="$1"

    # Attempt graceful destroy (force-off) — ignore error if already stopped
    virsh destroy "$vm_name" 2>/dev/null || true

    # Undefine and remove all storage volumes tracked by libvirt
    virsh undefine "$vm_name" --remove-all-storage 2>/dev/null || \
        virsh undefine "$vm_name" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# _backend_libvirt_get_vm_ip
#
# Polls for the VM's IPv4 address using virsh domifaddr (via DHCP lease data)
# and falls back to the qemu-guest-agent network interface query.
#
# Args:
#   $1  vm_name
#   $2  timeout_sec  (default: 60)
#
# Outputs: IP address on stdout; exits non-zero if not found within timeout.
# ---------------------------------------------------------------------------
_backend_libvirt_get_vm_ip() {
    local vm_name="$1"
    local timeout="${2:-60}"
    local start_time
    start_time=$(date +%s)

    while true; do
        local elapsed=$(( $(date +%s) - start_time ))
        if [[ $elapsed -ge $timeout ]]; then
            return 1
        fi

        # Primary: virsh domifaddr (uses DHCP leases — works without guest agent)
        local ip
        ip=$(virsh domifaddr "$vm_name" 2>/dev/null \
             | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' \
             | head -1)
        if [[ -n "$ip" ]]; then
            echo "$ip"
            return 0
        fi

        # Fallback: qemu-guest-agent network interface query
        ip=$(virsh qemu-agent-command "$vm_name" \
                 '{"execute":"guest-network-get-interfaces"}' 2>/dev/null \
             | jq -r '.return[].["ip-addresses"][]?
                       | select(.["ip-address-type"]=="ipv4")
                       | .["ip-address"]' 2>/dev/null \
             | grep -v "^127\." \
             | head -1)
        if [[ -n "$ip" ]]; then
            echo "$ip"
            return 0
        fi

        sleep 2
    done
}

# ---------------------------------------------------------------------------
# _backend_libvirt_add_dhcp
#
# Adds a DHCP host reservation to a libvirt network so the VM always receives
# the same IP address.  Failure is non-fatal — cloud-init configures the
# static IP independently.
#
# Args:
#   $1  network   — libvirt network name
#   $2  vm_name
#   $3  mac       — MAC address
#   $4  ip        — desired IP address
# ---------------------------------------------------------------------------
_backend_libvirt_add_dhcp() {
    local network="$1"
    local vm_name="$2"
    local mac="$3"
    local ip="$4"

    # Idempotent: skip if reservation already present
    if virsh net-dumpxml "$network" 2>/dev/null | grep -q "mac='$mac'"; then
        log_info "DHCP reservation for $mac already exists"
        return 0
    fi

    if virsh net-update "$network" add ip-dhcp-host \
           "<host mac='$mac' name='$vm_name' ip='$ip'/>" \
           --live --config 2>/dev/null; then
        log_success "DHCP reservation added"
    else
        log_warn "Could not add DHCP reservation (may need network restart)"
        log_info "Continuing — cloud-init will configure static IP"
    fi

    return 0
}

# ---------------------------------------------------------------------------
# _backend_libvirt_set_autostart
#
# Enables or disables VM autostart on host boot.
#
# Args:
#   $1  vm_name
#   $2  enable  — "true" to enable, any other value to disable
# ---------------------------------------------------------------------------
_backend_libvirt_set_autostart() {
    local vm_name="$1"
    local enable="${2:-true}"

    if [[ "$enable" == "true" ]]; then
        virsh autostart "$vm_name" > /dev/null 2>&1 || true
    else
        virsh autostart "$vm_name" --disable > /dev/null 2>&1 || true
    fi
}

# ---------------------------------------------------------------------------
# _backend_libvirt_vm_exists
#
# Returns 0 if the VM is defined in libvirt, 1 otherwise.
#
# Args:
#   $1  vm_name
# ---------------------------------------------------------------------------
_backend_libvirt_vm_exists() {
    local vm_name="$1"
    virsh dominfo "$vm_name" &>/dev/null
}
