#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_OUT="${LIVE_AGENT_CONFORMANCE_REPORT_OUT:-${ROOT_DIR}/conformance.live-agent.report.md}"
SERVER_LOG_OUT="${LIVE_AGENT_CONFORMANCE_SERVER_LOG_OUT:-${ROOT_DIR}/conformance.live-agent.server.log}"
RUN_ROOT="${LIVE_AGENT_CONFORMANCE_RUN_ROOT:-$(mktemp -d /tmp/agentic-live-agent-conformance.XXXXXX)}"
RAW_LOG="${RUN_ROOT}/cargo-test.log"
SYNTHETIC_SECRET_FIXTURE="${SYNTHETIC_SECRET_FIXTURE:-synthetic-secret-fixture-281}"
INSTANCE_ID="${CONFORMANCE_INSTANCE_ID:-inst-1}"
AGENT_CARD_URL="${CONFORMANCE_AGENT_CARD_URL:-/agents/${INSTANCE_ID}/.well-known/agent-card.json}"
RUNTIME_KIND="${CONFORMANCE_RUNTIME_KIND:-synthetic-deterministic-dispatch}"
RUNTIME_LOADOUT="${CONFORMANCE_RUNTIME_LOADOUT:-synthetic-live-agent-t3}"

redact() {
  python3 -c 'import sys; token=sys.argv[1]; data=sys.stdin.read(); print(data.replace(token, "<redacted-synthetic-secret>"), end="")' "${SYNTHETIC_SECRET_FIXTURE}"
}

cleanup() {
  local rc=$?
  if [[ -f "${RAW_LOG}" ]]; then
    redact < "${RAW_LOG}" > "${SERVER_LOG_OUT}" || true
  fi
  if [[ "${KEEP_LIVE_AGENT_CONFORMANCE_RUN:-0}" != "1" ]]; then
    rm -rf "${RUN_ROOT}"
  fi
  exit "${rc}"
}
trap cleanup EXIT

require_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "required tool missing: $1" >&2
    exit 1
  fi
}

write_report() {
  local status="$1"
  local commit
  local finished_at
  commit="$(git -C "${ROOT_DIR}" rev-parse HEAD 2>/dev/null || echo unknown)"
  finished_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  cat > "${REPORT_OUT}" <<EOF
# Live Agent Conformance Report

- status: ${status}
- management_commit: ${commit}
- management_binary: cargo test --manifest-path management/Cargo.toml -p agentic-sandbox-executor
- runtime_kind: ${RUNTIME_KIND}
- runtime_image_or_loadout: ${RUNTIME_LOADOUT}
- instance_id: ${INSTANCE_ID}
- agent_card_url: ${AGENT_CARD_URL}
- task_ids: generated by local executor TaskStore during test run
- terminal_states: completed, failed, canceled, rejected
- hitl_states: input-required, valid response accepted, invalid response rejected with 422
- adapter_command: bounded sandbox-agent-runner command form
- artifacts: synthetic adapter artifact with redacted synthetic secret fixture
- finished_utc: ${finished_at}
- server_log: ${SERVER_LOG_OUT}

## Assertions

- local deterministic live-agent dispatch covered completed, failed, rejected, HITL, and adapter-command scenarios
- existing cancel handler covered canceled terminal state with terminal_at
- only synthetic fixture values were used for redaction coverage
- exported logs redact the synthetic secret fixture as <redacted-synthetic-secret>
EOF
}

require_tool cargo
require_tool python3
mkdir -p "${RUN_ROOT}"

{
  echo "synthetic redaction fixture: ${SYNTHETIC_SECRET_FIXTURE}"
  cargo test --manifest-path "${ROOT_DIR}/management/Cargo.toml" -p agentic-sandbox-executor live_agent_t3 -- --nocapture
  cargo test --manifest-path "${ROOT_DIR}/management/Cargo.toml" -p agentic-sandbox-executor cancel_task_200_transitions -- --nocapture
} > "${RAW_LOG}" 2>&1

write_report "pass"
echo "live-agent conformance passed: report=${REPORT_OUT} log=${SERVER_LOG_OUT}"
