//! Task storage management
//!
//! Handles filesystem operations for task data, including inbox/outbox management.

use std::path::PathBuf;
use tokio::fs;
use tokio::io::AsyncWriteExt;
use tracing::{debug, info};

use super::task::Task;

/// Manages task storage on the filesystem
pub struct TaskStorage {
    tasks_root: PathBuf,
    agentshare_root: PathBuf,
}

impl TaskStorage {
    pub fn new(tasks_root: String, agentshare_root: String) -> Self {
        Self {
            tasks_root: PathBuf::from(tasks_root),
            agentshare_root: PathBuf::from(agentshare_root),
        }
    }

    /// Get path to task directory
    pub fn task_dir(&self, task_id: &str) -> PathBuf {
        self.tasks_root.join(task_id)
    }

    /// Get path to task inbox
    pub fn inbox_path(&self, task_id: &str) -> PathBuf {
        self.task_dir(task_id).join("inbox")
    }

    /// Get path to task outbox
    pub fn outbox_path(&self, task_id: &str) -> PathBuf {
        self.task_dir(task_id).join("outbox")
    }

    /// Get path to progress directory
    pub fn progress_path(&self, task_id: &str) -> PathBuf {
        self.outbox_path(task_id).join("progress")
    }

    /// Get path to artifacts directory
    pub fn artifacts_path(&self, task_id: &str) -> PathBuf {
        self.outbox_path(task_id).join("artifacts")
    }

    /// Get global read-only share path
    pub fn global_path(&self) -> PathBuf {
        self.agentshare_root.join("global-ro")
    }

    /// Create task directory structure
    pub async fn create_task_directory(&self, task_id: &str) -> Result<(), StorageError> {
        let task_dir = self.task_dir(task_id);
        let inbox = self.inbox_path(task_id);
        let outbox = self.outbox_path(task_id);
        let progress = self.progress_path(task_id);
        let artifacts = self.artifacts_path(task_id);

        // Create directories
        fs::create_dir_all(&task_dir).await?;
        fs::create_dir_all(&inbox).await?;
        fs::create_dir_all(&outbox).await?;
        fs::create_dir_all(&progress).await?;
        fs::create_dir_all(&artifacts).await?;

        // Initialize progress files
        let stdout_log = progress.join("stdout.log");
        let stderr_log = progress.join("stderr.log");
        let events_log = progress.join("events.jsonl");

        fs::File::create(&stdout_log).await?;
        fs::File::create(&stderr_log).await?;
        fs::File::create(&events_log).await?;

        info!("Created task directory structure: {:?}", task_dir);
        Ok(())
    }

    /// Write manifest to task directory
    pub async fn write_manifest(
        &self,
        task_id: &str,
        manifest_yaml: &str,
    ) -> Result<(), StorageError> {
        let path = self.task_dir(task_id).join("manifest.yaml");
        fs::write(&path, manifest_yaml).await?;
        debug!("Wrote manifest to {:?}", path);
        Ok(())
    }

    /// Write task prompt to inbox as TASK.md
    pub async fn write_task_prompt(&self, task_id: &str, prompt: &str) -> Result<(), StorageError> {
        let path = self.inbox_path(task_id).join("TASK.md");
        let content = format!(
            "# Task Instructions\n\n{}\n\n---\n*This file was generated by agentic-sandbox task orchestration.*\n",
            prompt
        );
        fs::write(&path, content).await?;
        debug!("Wrote TASK.md to {:?}", path);
        Ok(())
    }

    /// Write metadata JSON to outbox
    pub async fn write_metadata(&self, task: &Task) -> Result<(), StorageError> {
        let path = self.outbox_path(&task.id).join("metadata.json");
        let metadata = serde_json::json!({
            "task_id": task.id,
            "name": task.name,
            "state": task.state.to_string(),
            "created_at": task.created_at.to_rfc3339(),
            "started_at": task.started_at.map(|t| t.to_rfc3339()),
            "repository": {
                "url": task.repository.url,
                "branch": task.repository.branch,
                "commit": task.repository.commit,
            },
            "vm": {
                "name": task.vm_name,
                "ip": task.vm_ip,
                "profile": task.vm.profile,
            },
            "exit_code": task.exit_code,
            "error": task.error,
        });

        let content = serde_json::to_string_pretty(&metadata)?;
        fs::write(&path, content).await?;
        Ok(())
    }

    /// Append to stdout log
    pub async fn append_stdout(&self, task_id: &str, data: &[u8]) -> Result<(), StorageError> {
        let path = self.progress_path(task_id).join("stdout.log");
        let mut file = fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&path)
            .await?;
        file.write_all(data).await?;
        Ok(())
    }

    /// Append to stderr log
    pub async fn append_stderr(&self, task_id: &str, data: &[u8]) -> Result<(), StorageError> {
        let path = self.progress_path(task_id).join("stderr.log");
        let mut file = fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&path)
            .await?;
        file.write_all(data).await?;
        Ok(())
    }

    /// Append event to events.jsonl
    pub async fn append_event(
        &self,
        task_id: &str,
        event: &serde_json::Value,
    ) -> Result<(), StorageError> {
        let path = self.progress_path(task_id).join("events.jsonl");
        let mut file = fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&path)
            .await?;

        let line = format!("{}\n", serde_json::to_string(event)?);
        file.write_all(line.as_bytes()).await?;
        Ok(())
    }

    /// Read stdout log
    pub async fn read_stdout(&self, task_id: &str) -> Result<String, StorageError> {
        let path = self.progress_path(task_id).join("stdout.log");
        Ok(fs::read_to_string(&path).await.unwrap_or_default())
    }

    /// Read stderr log
    pub async fn read_stderr(&self, task_id: &str) -> Result<String, StorageError> {
        let path = self.progress_path(task_id).join("stderr.log");
        Ok(fs::read_to_string(&path).await.unwrap_or_default())
    }

    /// List artifacts in outbox
    pub async fn list_artifacts(&self, task_id: &str) -> Result<Vec<ArtifactInfo>, StorageError> {
        let artifacts_dir = self.artifacts_path(task_id);
        let mut artifacts = Vec::new();

        if !artifacts_dir.exists() {
            return Ok(artifacts);
        }

        let mut entries = fs::read_dir(&artifacts_dir).await?;
        while let Some(entry) = entries.next_entry().await? {
            let path = entry.path();
            if path.is_file() {
                let metadata = fs::metadata(&path).await?;
                let name = path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("")
                    .to_string();

                artifacts.push(ArtifactInfo {
                    name,
                    path: path.to_string_lossy().to_string(),
                    size_bytes: metadata.len(),
                    content_type: mime_guess::from_path(&path)
                        .first_or_octet_stream()
                        .to_string(),
                });
            }
        }

        Ok(artifacts)
    }

    /// Get total size of progress logs
    pub async fn get_progress_size(&self, task_id: &str) -> Result<u64, StorageError> {
        let progress_dir = self.progress_path(task_id);
        let mut total = 0u64;

        if progress_dir.exists() {
            let mut entries = fs::read_dir(&progress_dir).await?;
            while let Some(entry) = entries.next_entry().await? {
                if entry.path().is_file() {
                    total += fs::metadata(entry.path()).await?.len();
                }
            }
        }

        Ok(total)
    }

    /// Clean up task directory
    pub async fn cleanup_task(&self, task_id: &str) -> Result<(), StorageError> {
        let task_dir = self.task_dir(task_id);
        if task_dir.exists() {
            fs::remove_dir_all(&task_dir).await?;
            info!("Cleaned up task directory: {:?}", task_dir);
        }
        Ok(())
    }

    /// Check if task directory exists
    pub async fn task_exists(&self, task_id: &str) -> bool {
        self.task_dir(task_id).exists()
    }
}

/// Information about an artifact
#[derive(Debug, Clone)]
pub struct ArtifactInfo {
    pub name: String,
    pub path: String,
    pub size_bytes: u64,
    pub content_type: String,
}

/// Storage errors
#[derive(Debug, thiserror::Error)]
pub enum StorageError {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),

    #[error("JSON error: {0}")]
    Json(#[from] serde_json::Error),

    #[error("Task directory not found: {0}")]
    TaskNotFound(String),
}
